### ISSUE TITLE
Generate and send email to vendor

### ISSUE THREAD

**Issue by jvanderbiest** [CoditEU/lunchorder#39]
- [x] Get current order from docdb
- [x] transform to html
- [x] send email using job
- [ ] add company details to web.config to include in email

**Comment by tomkerkhove** [comment]
What mailing service will you use are a self-hosted account?

**Comment by jvanderbiest** [comment]
Free Plan

12,000 emails per month

https://sendgrid.com/pricing/ :)

2016-07-27 17:02 GMT+02:00 Tom Kerkhove <notifications@github.com>:
