### ISSUE TITLE
Use https

### ISSUE THREAD

**Issue by jvanderbiest** [CoditEU/lunchorder#71]
Have a look here:
https://www.troyhunt.com/everything-you-need-to-know-about-loading-a-free-lets-encrypt-certificate-into-an-azure-website/

and add a permenant redirect to https

**Comment by tomkerkhove** [comment]
Looks like this one is already there, can be resolved as well I presume?

**Comment by jvanderbiest** [comment]
https://github.com/CoditEU/lunchorder/wiki/Configure-HTTPS
